version: '3'
services:
  postgres-boilerplate:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - .data/postgres:/var/lib/postgresql/data

    restart: always

  pgadmin-boilerplate:
    image: fenglc/pgadmin4
    ports:
      - '5050:5050'
    restart: always
